using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Goobstation.Shared.CartridgeLoader.Cartridges;
using System.Reflection.PortableExecutable;

namespace Content.Goobstation.Client.CartridgeLoader.Cartridges;

/// <summary>
/// This container is the base <i>thing</i> that makes up the reporter livestream UI.`
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ReporterLivestreamUiFragment : BoxContainer
{

    public event Action? SubnetRefresh;

    public ReporterLivestreamUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        SubnetRefreshButton.OnPressed += _ => SubnetRefresh?.Invoke();
    }
    public void UpdateState(SharedReporterLivestreamUiState state)
    {
        SubnetIdLabel.Text = state.ActiveSubnet;
    }



}